quarkus.http.port=${QUARKUS_HTTP_PORT:8082}

quarkus.oidc.application-type=web-app
quarkus.oidc.auth-server-url=${QUARKUS_OIDC_AUTH_SERVER_URL:http://127.0.0.1:8080/realms/keycloak-demo}
quarkus.oidc.connection-delay=2S
quarkus.oidc.connection-retry-count=1
quarkus.oidc.connection-timeout=2S
quarkus.oidc.client-id=quarkus-app
quarkus.oidc.credentials.secret=${QUARKUS_OIDC_CREDENTIALS_SECRET:quarkus-secret}
quarkus.oidc.authentication.redirect-path=/oidc/callback
quarkus.oidc.authentication.restore-path-after-redirect=true
quarkus.oidc.authentication.cookie-path=/
quarkus.oidc.roles.role-claim-path=realm_access/roles
quarkus.oidc.logout.path=/logout
quarkus.oidc.logout.post-logout-path=/

quarkus.http.auth.permission.logout.paths=/logout
quarkus.http.auth.permission.logout.policy=authenticated

quarkus.log.category."io.quarkus.oidc".level=INFO
