bootstrap.servers=localhost:9092
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=org.apache.kafka.common.serialization.IntegerSerializer

security.protocol=SASL_PLAINTEXT
sasl.mechanism=OAUTHBEARER
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;
sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
sasl.oauthbearer.client.credentials.client.id=kafka-producer-app
sasl.oauthbearer.client.credentials.client.secret=kafka-producer-secret
sasl.oauthbearer.token.endpoint.url=http://127.0.0.1:8080/realms/keycloak-demo/protocol/openid-connect/token
sasl.login.connect.timeout.ms=5000
sasl.login.read.timeout.ms=5000
