security.protocol=SASL_PLAINTEXT
sasl.mechanism=OAUTHBEARER
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required clientId="kafka-cli" clientSecret="kafka-cli-secret";
sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerLoginCallbackHandler
sasl.oauthbearer.token.endpoint.url=http://keycloak:8080/realms/keycloak-demo/protocol/openid-connect/token
sasl.login.connect.timeout.ms=5000
sasl.login.read.timeout.ms=5000
